export const TRIPS__FETCH_TRIPS_SUCCESS = 'TRIPS__FETCH_TRIPS_SUCCESS';
export const TRIPS__FETCH_TRIP_SUCCESS = 'TRIPS__FETCH_TRIP_SUCCESS';
export const TRIPS__OPEN_REGISTER_TO_TRIP_MODAL = 'TRIPS__OPEN_REGISTER_TO_TRIP_MODAL';
export const TRIPS__CLOSE_REGISTER_TO_TRIP_MODAL = 'TRIPS__CLOSE_REGISTER_TO_TRIP_MODAL';
